name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1' # Mondays at 3 AM

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Check for base image updates
        id: check_base
        run: |
          BASE_IMAGE="php:${{ matrix.php-version }}-fpm-alpine"
          docker pull $BASE_IMAGE
          LATEST_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $BASE_IMAGE)
          echo "LATEST_DIGEST=$LATEST_DIGEST" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.php-version }}-${{ steps.check_base.outputs.LATEST_DIGEST }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.php-version }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: Dockerfile
          build-args: PHP_VERSION=${{ matrix.php-version }}
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php:${{ matrix.php-version }}-fpm-alpine
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
